allowlist = [
    'localhost', # local proxies
    'audio-sp-.*\.pscdn\.co', # audio
    'audio-fa\.scdn\.co', # audio
    'audio4-fa\.scdn\.co', # audio
    'charts-images\.scdn\.co', # charts images
    'daily-mix\.scdn\.co', # daily mix images
    'dailymix-images\.scdn\.co', # daily mix images
    'heads-fa\.scdn\.co', # audio (heads)
    'i\.scdn\.co', # cover art
    'lineup-images\.scdn\.co', # playlists lineup images
    'merch-img\.scdn\.co', # merch images
    'misc\.scdn\.co', # miscellaneous images
    'mosaic\.scdn\.co', # playlist mosaic images
    'newjams-images\.scdn\.co', # release radar images
    'o\.scdn\.co', # cover art
    'pl\.scdn\.co', # playlist images
    'profile-images\.scdn\.co', # artist profile images
    'seeded-session-images\.scdn\.co', # radio images
    't\.scdn\.co', # background images
    'thisis-images\.scdn\.co', # 'this is' playlists images
    'video-fa\.scdn\.co', # videos
    'content\.production\.cdn\.art19\.com', # podcasts
    'rss\.art19\.com', # podcasts
    '.*\.buzzsprout\.com', # podcasts
    'chtbl\.com', # podcasts
    'platform-lookaside\.fbsbx\.com', # Facebook profile images
    'genius\.com', # lyrics (genius-spicetify)
    '.*\.googlevideo\.com', # YouTube videos (Spicetify Reddit app)
    '.*\.gvt1\.com', # Widevine download
    'hwcdn\.libsyn\.com', # podcasts
    'traffic\.libsyn\.com', # podcasts
    'api.*-desktop\.musixmatch\.com', # lyrics (genius-spicetify)
    '.*\.podbean\.com', # podcasts
    'cdn\.podigee\.com', # podcasts
    'dts\.podtrac\.com', # podcasts
    'www\.podtrac\.com', # podcasts
    'www\.reddit\.com', # Reddit (Spicetify Reddit app)
    'audio\.simplecast\.com', # podcasts
    'media\.simplecast\.com', # podcasts
    'ap\.spotify\.com', # audio (access point)
    '.*\.ap\.spotify\.com', # resolved access points
    'api\.spotify\.com', # client APIs
    'api-partner\.spotify\.com', # album/artist pages
    'xpui\.app\.spotify\.com', # user interface
    'apresolve\.spotify\.com', # access point resolving
    'clienttoken\.spotify\.com', # login
    '.*dealer\.spotify\.com', # websocket connections
    'image-upload.*\.spotify\.com', # image uploading
    'login.*\.spotify\.com', # login
    '.*-spclient\.spotify\.com', # client APIs
    'spclient\.wg\.spotify\.com', # client APIs, ads/tracking (blocked in blacklist)
    'audio-fa\.spotifycdn\.com', # audio
    'seed-mix-image\.spotifycdn\.com', # mix images
    'download\.ted\.com', # podcasts
    'www\.youtube\.com', # YouTube (Spicetify Reddit app)
    'i\.ytimg\.com', # YouTube images (Spicetify Reddit app)
    'chrt\.fm', # podcasts
    'dcs.*\.megaphone\.fm', # podcasts
    'traffic\.megaphone\.fm', # podcasts
    'pdst\.fm', # podcasts
    'audio-ak-spotify-com\.akamaized\.net', # audio
    'audio4-ak-spotify-com\.akamaized\.net', # audio
    'heads4-ak-spotify-com\.akamaized\.net', # audio (heads)
    'audio4-ak\.spotify\.com\.edgesuite\.net', # audio
    'scontent.*\.fbcdn\.net', # Facebook profile images
    'audio-sp-.*\.spotifycdn\.net', # audio
    'dovetail\.prxu\.org', # podcasts
    'dovetail-cdn\.prxu\.org', # podcasts
]

denylist = [
    'https://spclient\.wg\.spotify\.com/ads/.*', # ads
    'https://spclient\.wg\.spotify\.com/ad-logic/.*', # ads
    'https://spclient\.wg\.spotify\.com/gabo-receiver-service/.*', # tracking
]
